#Jekyll Theme
# Pull the latest development version supporting skins
remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Enforce the light/dark skin default based on user preferences
minima:
  skin: auto

#Page info
title: 2026 AAAI Fall Symposium on Planning for a Better Planet
description: The website for the 2026 AAAI Fall Symposium on Planning for a Better Planet
